### ISSUE TITLE
README.md 내용 중 수정 제안

### ISSUE THREAD

**Issue by kjwoo31** [ai4r/Air-Clothing-MA#1]
anaconda에서 기본으로 제공하는 모듈과 명시된 opencv 외에도 matplotilb, nltk 모듈을 추가로 설치합니다.  
(darknet.py, build_clothing_vocab.py에서 사용)

> 4. install opencv
>  - (base)$ pip install opencv-python  

를 아래와 같이 변경하면 좋을 것 같습니다.    

> 4. install opencv, matplotlib, nltk
>  - (base)$ pip install opencv-python matplotlib nltk
<br/>

**Comment by chankyupark** [comment]
Thanks your comment. 
I update "install opencv, matplotlib" . (Now we don't need install nltk)
