### ISSUE TITLE
Dataset에 관한 질문

### ISSUE THREAD

**Issue by kjwoo31** [ai4r/Air-Clothing-MA#2]
성능 확인을 위해 Clothing-MA 모델에 대한 데이터셋을 사용하고 싶은데, 모델 학습에 사용한 train data, test data를 못 찾겠습니다. 혹시 데이터셋이 있는 위치를 알려주실 수 있나요?

**Comment by chankyupark** [comment]
I'm sorry we don't publish Clothing-MA dataset as our privacy policy.
