### ISSUE TITLE
demo 파일에서 import Vocabulary 부분을 지워야 합니다.

### ISSUE THREAD

**Issue by kjwoo31** [ai4r/Air-Clothing-MA#3]
현재 file_demo.py, cam_demo.py를 실행하였을 때 모두 아래와 같은 에러가 발생합니다.

>Traceback (most recent call last):
>  File "cam_demo.py", line 10, in <module>
>    from build_clothing_vocab import Vocabulary
>ModuleNotFoundError: No module named 'build_clothing_vocab'

 7.3. update에서 build_clothing_vocab.py를 삭제하면서 발생하는 문제인 것 같습니다.
 file_demo.py, cam_demo.py의 10번째 줄의 'from build_clothing_vocab import Vocabulary' 부분을 삭제하였더니 정상적으로 작동하였습니다.

**Comment by chankyupark** [comment]
I'm temporarily doing some modification on this project. 
This issue is now fixed.
