### ISSUE TITLE
Awesome Repo ! Quick Question about re-training the encoder.

### ISSUE THREAD

**Issue by EmpireofKings** [ai4r/Air-Clothing-MA#4]
Hello, thank you for this awesome repo !

This is not an issue, everything works. Its more of a question. I havent worked much with encoders, but i like its performance compared to running secondary classifiers to extract ROI attribute information. I would like to expand on this repo. and create my own encoder. 

Can you share any references or point me in the direction of a repo that shows how to train an encoder that works like the one you provided ?

Thank you

**Comment by chankyupark** [comment]
My response is so late. sorry about that.
reference site : https://github.com/wangxiao5791509/Pedestrian-Attribute-Recognition-Paper-List 
you can find good references you are interested in topics.
